### ISSUE TITLE
Porting to openstack

### ISSUE THREAD

**Issue by iahmad-khan** [oracle/terraform-kubernetes-installer#10]
Hi , 

Does oracle use some flavor of open-stack?  If yes , I want to discuss the possibility  of porting this project to a generic open-stack installation. What major changes will be needed to make this work on any latest open-stack installation?

Thanks.

**Comment by jlamillan** [comment]
Ijaz, 

I can't speak to whether Oracle's Cloud Infrastructure (OCI) has any support for OpenStack. The goal of this project was simply to provide a basic set of Terraform configs that leverages the [OCI provider](https://github.com/oracle/terraform-provider-oci) to provision the bare metal instances, network components, volumes, load balancers, etc. that are required for running for running HA Kubernetes cluster. AFAIK, the OCI provider does not use OpenStack, but plugs in to the various native REST API exposed by Oracle Cloud Infrastructure.
