### ISSUE TITLE
Create a seclist rule for ICMP for all the custom security lists

### ISSUE THREAD

**Issue by srirg** [oracle/terraform-kubernetes-installer#107]
As mentioned in the below documentation, we need a  ICMP type 3 code 4 rule defined to any new security list we create for the installer as we see the ssh just hangs at times after the setup.

https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Concepts/securitylists.htm#Stateful

Important: The preceding rule is critical for establishing a connection to your instances. If you do not use the default security list, make sure to add the preceding ICMP type 3 code 4 rule to any new security list you create. Without it, you can experience connectivity issues. For more information, see Hanging Connection

**Comment by jlamillan** [comment]
@srirg I have some feedback for your PR
