### ISSUE TITLE
Cluster creation failed because of intermittent failure in getting etcd discovery url 

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-kubernetes-installer#12]
Intermittently, the call to https://discovery.etcd.io can fail, which causes the following invalid discovery token to be generated in the `generated` folder:

```
jemillanmbp:generated jessem$ cat discoverye3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 
Unable to generate token
```
This situation in turn leads to an invalid parameter being passed to `-discovery` in `terraform-kubernetes-installer/instances/etcd/cloud_init/bootstrap.template.sh`:

```
docker run -d \
	-p 2380:2380 -p 2379:2379 \
	-v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
	--net=host \
	quay.io/coreos/etcd:${etcd_ver} \
	/usr/local/bin/etcd \
	-name $HOSTNAME \
	-advertise-client-urls http://$IP_LOCAL:2379 \
	-listen-client-urls http://$IP_LOCAL:2379,http://127.0.0.1:2379 \
	-listen-peer-urls http://0.0.0.0:2380 \
	-discovery "Unable to generate token"
```

This causes the cluster to fail to come up properly.

We are moving away from using the discovery URL, but in the meantime, we should not try to create a cluster if we failed to get a discovery url.

**Comment by duhang** [comment]
this issue can be easily fixed by adding --retry 3 to the curl command in
https://github.com/oracle/terraform-kubernetes-installer/blob/master/datasources.tf

  curl --retry 3 https://discovery.etcd.io/new?size=${var.etcdAd1Count + var.etcdAd2Count + var.etcdAd3Count}

**Comment by jlamillan** [comment]
This issue should be resolved with this [MR](https://github.com/oracle/terraform-kubernetes-installer/pull/90). Will reopen if seen again.
