### ISSUE TITLE
Separate security list for NAT instances

### ISSUE THREAD

**Issue by srirg** [oracle/terraform-kubernetes-installer#123]
Currently there is a limit of 50 rules for a Security List in OCI. With the NAT Security list across public LBR
s we are reaching the limit so we need to have a separate security list for the NAT Subnets.

Service limits.
https://docs.us-phoenix-1.oraclecloud.com/Content/General/Concepts/servicelimits.htm

Limits
Inbound or outbound rules | Security list | 50 ingress rules50 egress rules

**Comment by rohitkoul** [comment]
This should get resolved should #54 be done.

**Comment by srirg** [comment]
the [PR ](https://github.com/oracle/terraform-kubernetes-installer/pull/146) should fix this.
