### ISSUE TITLE
Document exposing a service with an OCI load balancer (Cloud Controller Manager)

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-kubernetes-installer#128]
The cluster is now integrated with the OCI [Cloud Controller Manager](https://github.com/oracle/oci-cloud-controller-manager) (CCM). As a result, creating a service of type `--type=LoadBalancer` will expose the pods to the Internet using an OCI Load Balancer.

**Comment by jlamillan** [comment]
[Done](https://github.com/oracle/terraform-kubernetes-installer/blob/master/docs/example-deployments.md).

**Comment by alistar79** [comment]
@jlamillan Is there any way to use the hostname or path functionality of the OCI LBs to route different paths or hostnames to different k8s service definitions? The mapping of 1:1 service to LB has us running out of LBs pretty fast! Seems the limit for 100mb LB is 3 on our account? 

Looking for a workaround currently.  Can only think of exposing services to a ports on the host then using nginx to intelligently route to those ports

**Comment by jlamillan** [comment]
Yes, check out [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/), which sits in front of your Kubernetes Services and routes traffic based on incoming paths or sub-domains.

e.g. 

foo.com/bar/ => OCI LB => Ingress => routes to the bar service based on /bar/ path
baz.foo.com => OCI LB => Ingress  => routes to the baz service based on baz sub-domain

You'll first need to deploy an "Ingress controller" to your cluster that actually routes the requests based on the Ingress Resource. I typically use the [NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx) in my clusters.
