### ISSUE TITLE
tls_self_signed_cert allowed_uses missing "digital_signature"

### ISSUE THREAD

**Issue by rjeberhard** [oracle/terraform-kubernetes-installer#134]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform --version
Terraform v0.11.2
+ provider.null v1.0.0
+ provider.oci (unversioned)
+ provider.random v1.1.0
+ provider.template v1.0.0
+ provider.tls v1.0.1
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

providers {
 oci = “/Users/bmoyers/oci_provider/darwin_amd64/terraform-provider-oci_v2.0.6”
}
</details>

### Terraform Installer for Kubernetes Version

<details>
# The version/tag/release or commit hash (of this project) the issue occurred on
</details>

### Input Variables

<details>
# Values of non-sensitive input variables

</details>

### Description of issue:

We are in the process of making open-source a Kubernetes operator for Oracle WebLogic.  Our internal testing and an external alpha tester discovered that the operator could not authenticate to the API server using a service account from inside the cluster because of this issue.  The original issue is here: https://github.com/oracle/weblogic-kubernetes-operator/issues/19

The fix is to add "digital_signature" as another entry in allowed_uses.

**Comment by jlamillan** [comment]
Thanks for the bug report!

**Comment by rjeberhard** [comment]
@jlamillan Jesse, sorry for this, but the customer is telling me that I made a mistake with the PR.  It's my fault.  The addition of "digital_signature" was supposed to go in the allowed_uses for the second resource, that for "api-server".  Can you please reopen this and I'll try a new PR?  Thanks.

**Comment by jlamillan** [comment]
Not problem. Reverted [here](https://github.com/oracle/terraform-kubernetes-installer/commit/65ee84a2964fca3639118a25c7a0b9328de11363) and fixed [here](https://github.com/oracle/terraform-kubernetes-installer/commit/80522e43ea53440047bf7486633833f10d81b7d8). Look good?
