### ISSUE TITLE
Support customizable boot volume size on Worker Nodes

### ISSUE THREAD

**Issue by j0nr33v3** [oracle/terraform-kubernetes-installer#147]
Request to support customizable boot volume size on worker nodes

**Comment by jlamillan** [comment]
Assuming I understand the request correctly, this is already supported via the following optional Input Variables:

name                                | default                 | description
------------------------------------|-------------------------|------------
worker_iscsi_volume_create          | "false"                 | boolean flag indicating whether or not to attach an iSCSI volume to attach to each worker node
worker_iscsi_volume_size            | unset                   | optional size of an iSCSI volume to attach to each worker
worker_iscsi_volume_mount           | /var/lib/docker         | optional mount path of iSCSI volume when worker_iscsi_volume_size is set
