### ISSUE TITLE
(enhancement) Add new import variables to control whether instances, subnets, lbs are public (default) or private

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-kubernetes-installer#15]
Based on some early internal feedback, we should let users control whether instances, load-balancers, subnets are public or private.

**Comment by orisvscs** [comment]
ISV reported this as a critical need, so would be good to support this scenario.

**Comment by duhang** [comment]
Is there any ETA for this issue being resolved in near future?
Private instances/subnets/lbr are must-have according to our Threat-Model.

**Comment by jlamillan** [comment]
I'm working on this now and hope to have something soon.

The change was a bit involved than just prohibiting public IPs on the instances and load-balancers since instances need access to the internet during the bootstrap phase. But here is our approach:

If the `tbd_private_cluster` input variable is set to true:

1. The etcd, master, and worker subnets, instances, and load-balancers, will be private - meaning they will not have public IP addresses.
2. We'll provision a NAT instance in the VCN that is on a public subnet and connected to the Internet.
2. While the etcd, master, and worker instances instances are initializing they will access the internet to download software through the NAT instance.
3. After the cluster is provisioned, the user can optionally tear down the NAT instance, completing the private_cluster installation.

**Comment by duhang** [comment]
Thanks for the update! I'm glad to try it out once the NAT instance is implemented.

**Comment by andytael** [comment]
If the .ssh/config file could be created yo jump through the NT server it would be awesome, that will simplify as yuo don't have to go to the NAT(Bastion) first and then connect to the server on the private NW.

**Comment by jlamillan** [comment]
> If the .ssh/config file could be created yo jump through the NT server it would be awesome, that will simplify as yuo don't have to go to the NAT(Bastion) first and then connect to the server on the private NW.

Yeah, that was what we were thinking.
