### ISSUE TITLE
failed to determine hostname for master nodes

### ISSUE THREAD

**Issue by samdgz** [oracle/terraform-kubernetes-installer#153]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
v0.10.8
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
[INFO] terraform-provider-oci 2.0.2
</details>

### Terraform Installer for Kubernetes Version

<details>
# The version/tag/release or commit hash (of this project) the issue occurred on
</details>

### Input Variables

<details>
# Values of non-sensitive input variables
terraform apply -auto-approve=true -var etcdAd1Count=1 -var etcdAd2Count=1 -var etcdAd3Count=1 -var etcdLBShape=100Mbps -var etcdShape=VM.Standard1.4 -var k8sMasterAd1Count=1 -var k8sMasterAd2Count=1 -var k8sMasterAd3Count=1 -var k8sWorkerAd1Count=1 -var k8sWorkerAd2Count=1 -var k8sWorkerAd3Count=1 -var master_ssh_ingress=0.0.0.0/0 -var worker_ssh_ingress=0.0.0.0/0 -var etcd_ssh_ingress=0.0.0.0/0 -var master_https_ingress=0.0.0.0/0 -var worker_nodeport_ingress=0.0.0.0/0 -var k8sMasterLBShape=400Mbps -var k8sMasterShape=VM.Standard2.1 -var k8sWorkerShape=VM.Standard1.16 -var private_key_password=**** -var etcd_iscsi_volume_create=true -var k8s_ver=1.7.9 -var encryption_secret=Ks41pKjxVPfv7GYDzihfYIZnGPaMToSR7ojZT0JTCYg= -var natInstanceShape=VM.Standard1.2 -var nat_instance_ad1_enabled=true -var nat_instance_ad2_enabled=true -var nat_instance_ad3_enabled=true -var etcd_lb_access=public -var etcd_maintain_private_ip=true -var control_plane_subnet_access=private -var k8s_dashboard_ver=1.7.1
</details>

### Description of issue:
After master nodes are registered as unschedulable nodes, PODs of node-exporter daemonset are now running in the master nodes. However, Prometheus operator fails to list these PODs as scraped targets due to the following errors:

ts=2018-02-09T19:10:28Z caller=operator.go:341 component=prometheusoperator msg=syncing nodes into Endpoints object failed, err=failed to determine hostname for node (k8s-master-ad1-0.k8smasterad1.k8sbmcs.oraclevcn.com): host address unknown.

**Comment by jlamillan** [comment]
Can the node itself perform a DNS lookup of `k8s-master-ad1-0`?

```
[root@k8s-master-ad1-0 opc]# nslookup k8s-master-ad1-0
```

Is the `kube-dns` pod and service running?

```
[root@k8s-master-ad1-0 opc]# kubectl get pod,svc -n kube-system | grep dns
```

What does the `/etc/resolv.conf` file look like from the node-exporter pod running on the master node(s)?

```
[root@k8s-master-ad1-0 opc]#  kubectl exec -it node-exporter-XXXXXX -n kube-system cat /etc/resolv.conf 
```

**Comment by samdgz** [comment]
kubectl exec -it node-exporter-57bwg -- /bin/sh
/ $ nslookup k8s-master-ad1-0.k8smasterad1.k8sbmcs.oraclevcn.com
Server:    169.254.169.254
Address 1: 169.254.169.254

Name:      k8s-master-ad1-0.k8smasterad1.k8sbmcs.oraclevcn.com
Address 1: 10.0.30.2 k8s-master-ad1-0.k8smasterad1.k8sbmcs.oraclevcn.com
/ $ cat /etc/resolv.conf
nameserver 169.254.169.254
search k8sbmcs.oraclevcn.com k8smasterad1.k8sbmcs.oraclevcn.com

**Comment by samdgz** [comment]
kube-dns is running

**Comment by samdgz** [comment]
Fixed by removing HostNetwork setting.
