### ISSUE TITLE
oci flex volume provisioner issue

### ISSUE THREAD

**Issue by srirg** [oracle/terraform-kubernetes-installer#154]
With the latest revision, we're seeing the below issue during the flex volume provisioner for consul stateful sets.

Below is the events sections from the describe pod consul-0
Events:
  FirstSeen	LastSeen	Count	From								SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----								-------------	--------	------			-------
  13m		13m		2	default-scheduler								Warning		FailedScheduling	PersistentVolumeClaim is not bound: "datadir-consul-0" (repeated 4 times)
  12m		12m		1	default-scheduler								Normal		Scheduled		Successfully assigned consul-0 to k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com
  12m		12m		1	kubelet, k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "statsd-conf" 
  12m		12m		1	kubelet, k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "config" 
  12m		12m		1	kubelet, k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-dwqzx" 
  10m		1m		5	kubelet, k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com			Warning		FailedMount		Unable to mount volumes for pod "consul-0_default(84775cd2-169d-11e8-8867-00001700c7f5)": timeout expired waiting for volumes to attach/mount for pod "default"/"consul-0". list of unattached/unmounted volumes=[datadir]
  10m		1m		5	kubelet, k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com			Warning		FailedSync		Error syncing pod
  12m		33s		14	attachdetach									Warning		FailedMount		AttachVolume.Attach failed for volume "abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa" : invalid character 'p' looking for beginning of value

[opc@k8s-master-ad1-0 oracle~oci]$ more oci_flexvolume_driver.log 
2018/02/21 00:14:59 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:14:59 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:14:59 Command result: {"status":"Success"}
2018/02/21 00:14:59 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:14:59 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:14:59 Command result: {"status":"Success"}
2018/02/21 00:15:29 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:15:29 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:15:29 Command result: {"status":"Success"}
2018/02/21 00:15:29 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:15:29 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:15:29 Command result: {"status":"Success"}
2018/02/21 00:15:56 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:15:56 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:15:56 Command result: {"status":"Success"}
2018/02/21 00:15:56 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:15:56 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci init' called with []
2018/02/21 00:15:56 Command result: {"status":"Success"}
2018/02/21 00:24:03 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:03 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci getvolumename' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"}]
2018/02/21 00:24:03 Command result: {"status":"Not supported","message":"getvolumename is broken as of kube 1.6.4"}
2018/02/21 00:24:03 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:03 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:03 Failed to decode cache: EOF
2018/02/21 00:24:03 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:04 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:04 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:04 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:06 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:06 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:06 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:08 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:08 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:08 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:13 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:13 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:13 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:22 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:22 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:24:38 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:24:38 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:24:39 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:25:11 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:25:11 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:25:11 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:26:16 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:26:16 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:26:16 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:28:18 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:28:18 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:28:18 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:30:21 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:30:21 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:30:21 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:32:24 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:32:24 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
ublic ip     :32:24 Unable to find OCI instance by displayname trying hostname/p--More--(88%)
2018/02/21 00:34:26 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:34:26 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:34:27 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:36:29 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:36:29 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:36:29 Unable to find OCI instance by displayname trying hostname/public ip
2018/02/21 00:38:31 OCI FlexVolume Driver version: 0.5.1 (c832ef7)
2018/02/21 00:38:31 '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/oracle~oci/oci attach' called with [{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"abyhqljse62nsbur2w43h4ad365tcxawjygx35vicprthfghnztzygooafpa","kubernetes.io/readwrite":"rw"} k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com]
2018/02/21 00:38:32 Unable to find OCI instance by displayname trying hostname/public ip

**Comment by garthy** [comment]
This is fixed in https://github.com/oracle/oci-flexvolume-driver/pull/62

**Comment by jlamillan** [comment]
I believe this issue was resolved by this [PR](https://github.com/oracle/terraform-kubernetes-installer/pull/157). @garthy could you confirm and close?
