### ISSUE TITLE
variable to enable/disable flex volume provisioner

### ISSUE THREAD

**Issue by srirg** [oracle/terraform-kubernetes-installer#155]
We need a variable to enable/disable the flex volume provisioner.

**Comment by garthy** [comment]
Why?

**Comment by srirg** [comment]
so that we have a static way to do the mounts as well. Currently we're blocked due to this issue [154](https://github.com/oracle/terraform-kubernetes-installer/issues/154l) and our existing configuration has static mounts and we cannot uptake the latest due to it. the flag should provide a way to uptake the latest changes.

**Comment by garthy** [comment]
Just unset the default storage provider from oci?

**Comment by srirg** [comment]
Is there a command to do it?

**Comment by garthy** [comment]
This is what the installer does to set default. 
```
kubectl patch storageclass oci -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```
So I guess change true to false will disable it?

**Comment by srirg** [comment]
Thanks, I will give it a try.
