### ISSUE TITLE
${path.module}/generated in bashsource.tf

### ISSUE THREAD

**Issue by xinnong-wang** [oracle/terraform-kubernetes-installer#163]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.3

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
[INFO] terraform-provider-oci 2.0.6

</details>

### Terraform Installer for Kubernetes Version

<details>
# The version/tag/release or commit hash (of this project) the issue occurred on
</details>

### Input Variables

<details>
# Values of non-sensitive input variables

</details>

### Description of issue:

Directory of `generated` in bashsource.tf is inconsistent.
datasources.tf
`mkdir -p ${path.root}/generated`

kubernetes/kubeconfig/kubeconfig.tf
`export KUBECONFIG="${path.root}/generated/kubeconfig"`

bashsource.tf:
`command = "echo \"export KUBECONFIG=${path.module}/generated/kubeconfig\" > source.sh "`
`ssh -i ${path.module}/generated/instances_id_rsa`

`${path.module}/generated` should be changed to `${path.root}/generated`

**Comment by garthy** [comment]
Is this due to trying to use the terraform installer as a module?

**Comment by garthy** [comment]
This is fixed in master
