### ISSUE TITLE
Add support for new OCI Terraform provider v2.

### ISSUE THREAD

**Issue by dhanmm** [oracle/terraform-kubernetes-installer#17]
Oracle Cloud Infrastructure provider has been updated since this Installer was published and breaks the TF configs. The latest version I tried (v2.0.1) does not work for the instructions given for terraform-kubernetes-installer. I had to install an earlier version (v1.0.18) of the provider before the name change was done to successfully install with this installer.

**Comment by jlamillan** [comment]
Yes, we tried to be clear on the README by recommending and linking to version: v1.0.18.  We have a [branch](https://github.com/oracle/terraform-kubernetes-installer/tree/jemillan/rename_baremetal_oci) where we will make the switch soon.
