### ISSUE TITLE
oci_core_virtual_network.CompleteVCN: Status: 404; Code: NotAuthorizedOrNotFound;

### ISSUE THREAD

**Issue by craigbarrau** [oracle/terraform-kubernetes-installer#21]
The issue should be easy to reproduce with the following:

1. sign up for OCI trial
2. clone this repo
3. `terraform init`
4. enter terraform.tfvars details
5. `terraform plan`. **This works which seems to prove the credentials are correct**
6. `terraform apply`. 
This fails after 2 minutes with
```
Error applying plan:

1 error(s) occurred:

* module.vcn.oci_core_virtual_network.CompleteVCN: 1 error(s) occurred:

* oci_core_virtual_network.CompleteVCN: Status: 404; Code: NotAuthorizedOrNotFound; OPC Request ID: /OMITTED; Message: Authorization failed or requested resource not found.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

After the failure I ran `terraform destroy` and it cleaned by successfully.

Any missing prerequisites ? Or is this a legitimate defect?

**Comment by jlamillan** [comment]
Craig,

This is most likely not a defect these scripts or this project. It looks like to me like either a authentication or authorization error with Oracle Cloud Infrastructure (formally BMC / Bare Metal Cloud). 

Double check that the user / tenancy / compartment OCIDs. Also check that the user has permission to create artifacts in the tenancy / compartment and that you've uploaded your PEM public key to the user in the Console and you are using the PEM private key for the private_key_path for the provider.

**Comment by craigbarrau** [comment]
If it is an auth issue why did plan work and also apply created other
resources for 2 mins before it failed with that error?
Lastly this is a vanilla trial instance of OCI so if there is some
dependency on that side you might want to document as I assume others would
hit this issue as well.

I also used the credentials with OCi curl example and it worked fine.

Can you provide a little more info regarding “checking the user has
permissions to create artifacts in the tenancy”? Shall I just make sure I
can manually create an instance in the same compartment? And if so, what
next? Any other debug tips?

**Comment by jlamillan** [comment]
When you say that "apply created other resources", do you mean resources in BMC in your compartment?

The scripts create a number of Terraform resources like certs, tokens, etc. Though, as far as I am aware, the first actual _OCI_ resource that gets created is the CompleteVCN, which is what is failing for you:

```
* module.vcn.oci_core_virtual_network.CompleteVCN: 1 error(s) occurred:

* oci_core_virtual_network.CompleteVCN: Status: 404; Code: NotAuthorizedOrNotFound; OPC Request ID: /OMITTED; Message: Authorization failed or requested resource not found.
```

As a debug step to take the scripts out of the equation, you could use the OCI console to see if the scripts created any network or compute resources in the expected compartment. If it did not, you could try manually crating a Virtual Cloud Network resource.

**Comment by jlamillan** [comment]
FYI, I was able to reproduce what you are seeing by removing my user from the group that granted me rights to manage resources in my target compartment:

```
terraform apply
...
terraform creating local resources such as certs, tokens, etc.
....
Error applying plan:

1 error(s) occurred:

* module.vcn.oci_core_virtual_network.CompleteVCN: 1 error(s) occurred:

* oci_core_virtual_network.CompleteVCN: Status: 404; Code: NotAuthorizedOrNotFound; OPC Request ID: /OMITTED
; Message: Authorization failed or requested resource not found.
```

So, in terms of the prerequisites that are not called out in this project, you'd need to:

1. Create a compartment e.g. kubernetes
2. Create a group e.g. kubernetes-installer
3. Create a Policy for the group e.g. `Allow group kubernetes-installer to manage all-resources in compartment kubernetes`
4. Create a user
5. Upload an API key for the user
6. Add User to the kubernetes-installer group

**Comment by craigbarrau** [comment]
Perfect, thanks for that! I will try it out shortly.

**Comment by craigbarrau** [comment]
At first, I found that I didn't have permissions to add a new policy for a new kubernetes compartment e.g.
<img width="681" alt="screenshot 2017-10-11 16 27 13" src="https://user-images.githubusercontent.com/7553951/31425659-8b0b08d0-aea3-11e7-857e-6afecf9b3d0f.png">
However, I later discovered that the root compartment OCID is that same as the tenancy OCID so when I set them the same, the "terraform apply" worked.

**Comment by jlamillan** [comment]
Glad to hear!
