### ISSUE TITLE
Move to Kubernetes 1.8 in terraform-kubernetes-installer

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-kubernetes-installer#31]
We need to move to Kubernetes 1.8 in the terraform-kubernetes-installer. This task also includes making whatever changes are necessary to the bootstrap scripts, and re-running all tests including Kubernetes conformance tests.

In addition, we should consider moving to the latest:
* Docker version
* etcd version
* Flannel version

**Comment by j0nr33v3** [comment]
Also submit conformance results to CNCF as part of this move

**Comment by jrosinsk** [comment]
running with k8s v1.8.3:

 kubelet: Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a         future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set.         In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.

**Comment by jrosinsk** [comment]
kubelet: W1116 20:54:28.065317   14624 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set explicitly

**Comment by jrosinsk** [comment]
kubelet: E1116 20:54:28.177836   14624 file.go:149] Can't process manifest file "/etc/kubernetes/manifests/worker-kubeconfig.yaml": /etc/kubernetes/manifests/worker-kubeconfig.yaml: couldn't parse as pod(no kind "Config" is registered for version "v1"), please check manifest file.

**Comment by pravarsh** [comment]
When is this issue expected to fix?

**Comment by jlamillan** [comment]
Pretty sure it's next on the list after integrating with the oci-flexolume-driver, oci-volume-provisioner and oci-cloud-controller-manager is complete.

**Comment by jlamillan** [comment]
FYI, we just moved to 1.7.10.

**Comment by activeshadow** [comment]
FYI, I used the `terraform-kubernetes-installer` today with the following variables in `terraform.tfvars` to successfully deploy a cluster in OCI:

```
etcd_ver          = "v3.2.2"
flannel_ver       = "v0.9.1"
k8s_ver           = "1.8.6"
k8s_dns_ver       = "1.14.5"
k8s_dashboard_ver = "1.8.2"
```

I noticed the OCI Cloud Controller Manager gets installed, but not the OCI FlexVolume Driver / OCI Volume Provisioner. I'm assuming I can install these manually? When will they be included in the terraform installer?

**Comment by jlamillan** [comment]
@garthy

**Comment by garthy** [comment]
I should have a PR ready tomorrow.

**Comment by jlamillan** [comment]
Confirmed that a cluster based on the following input variables works fine:

```
etcd_ver          = "v3.2.2"
flannel_ver       = "v0.9.1"
k8s_ver           = "1.8.6"
k8s_dns_ver       = "1.14.5"
k8s_dashboard_ver = "1.8.2"
```

I did run into an issue accessing the dashboard:

```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.99.18.3:9090/'
```

which you can work around by using the following modified URL (note the `http` instead of `https` in the URL):

http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/

**Comment by jlamillan** [comment]
The [default version](https://github.com/oracle/terraform-kubernetes-installer/blob/master/docs/input-variables.md#software-versions-installed-on-oci-instances) of `k8s_ver` is now `1.8.5`.
