### ISSUE TITLE
Provide instructions about how to upgrade k8s to newer version

### ISSUE THREAD

**Issue by zjmtlab** [oracle/terraform-kubernetes-installer#34]
Since there is no kubeadm, so can't use kubeadm to upgrade k8s.
It will be best if can provide a instruction for upgrade k8s with this installer. Thanks!

**Comment by zjmtlab** [comment]
Hi jlamilan,
   Do you have a recommaned proposal for the k8s upgrade? especially for master node.
   Don't need formal document, just briefly describe the steps can help a lot.
Thanks!

**Comment by jlamillan** [comment]
_One_ way to upgrade your cluster is by incrementally changing the value of the `k8s_ver` input variable on your master and then worker nodes.

For example, the command `terraform apply -var k8s_ver=1.7.5 -target=module.instances-k8sworker-ad1` would (1) drain _all_ worker nodes in AD1 to your nodes in AD2 and AD3 (2) then destroy all worker nodes in AD1, (3) re-create worker nodes in AD1 using Kubernetes 1.7.5, and finally (4) have them re-join the cluster. 

If you have more than one worker in an AD, you can upgrade worker nodes individually using the subscript operator e.g. `terraform plan -var k8s_ver=1.7.5 -target=module.instances-k8smaster-ad1.oci_core_instance.TFInstanceK8sMaster[1]`

Depending on your tolerance for failure, I would smoke test this approach on a stand-by cluster to weed out pitfalls and ensure our scripts are compatible with the version of Kubernetes you are trying to use - we have also not tested other versions of Kubernetes other than the the default version (1.7.4).
