### ISSUE TITLE
(enhancement) allow placement of NAT instances in a separate subnet than that of k8s master LB

### ISSUE THREAD

**Issue by rohitkoul** [oracle/terraform-kubernetes-installer#54]
### Description of issue:

Currently, when `control_plane_subnet_access=private`  a _single_ set of public subnets (public-subnet-AD[1-3], are provisioned which are shared by the NAT instances as well as the k8s master LB (if `k8s_master_lb_access=public`). As a consequence, this means that the NAT and the k8s master LB share the same security list.  
This was thought to be OK with the assumption that there would not be any overlap between the ingress between the two (e.g. 22 for the NAT, 443 for the LB) . However, there could be corner cases wherein the aforementioned assumption doesn't hold true and thereby the topology is not desirable.  (redacting the internal usecase from this public filing) As discussed with @jlamillan , If we could add another flag that separates the two subnets - that would be ideal.

**Comment by srirg** [comment]
the [PR 146](https://github.com/oracle/terraform-kubernetes-installer/pull/146) should fix this issue.

**Comment by rohitkoul** [comment]
commit: https://github.com/oracle/terraform-kubernetes-installer/commit/8db4ad3eda2526e3db2b6b6138d3412840c9207f
