### ISSUE TITLE
Add support for creating a service with --type=LoadBalancer

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-kubernetes-installer#6]
This will required creating an LB managed by BMC in some form.

**Comment by owainlewis** [comment]
This work is complete and can be done by integrating the oci-cloud-controller-manager once it's released.

**Comment by orisvscs** [comment]
Let us know when/how one can test this.

**Comment by lucassrg** [comment]
@owainlewis Having access to this component from the terraform installer would allow us to support any application workload, including the ones from kubeapps.com / Helm project - which depends on the LoadBalancer service type.

**Comment by jlamillan** [comment]
FYI - this is the top item in our backlog at the moment.

**Comment by jlamillan** [comment]
We have a [branch](https://github.com/oracle/terraform-kubernetes-installer/tree/jlamillan/gb-oci-cloud-controller) that is just about ready to resolve this issue.

**Comment by jlamillan** [comment]
Filed CCM issue [here](https://github.com/oracle/oci-cloud-controller-manager/issues/116).

**Comment by jlamillan** [comment]
This is complete. Using the latest Installer, you can now create an OCI Load Balancer when creating a Kubernetes service.

e.g. 

```
kubectl run nginx --image=nginx --port=80 --replicas=3
kubectl  expose deployment nginx --type LoadBalancer
```
