### ISSUE TITLE
Add Support For Persistent Storage / Disk Integration

### ISSUE THREAD

**Issue by j0nr33v3** [oracle/terraform-kubernetes-installer#7]
Enable support for Persistent Volumes and Persistent Volume Claims

**Comment by orisvscs** [comment]
ISV needs this feature soon, so would be great to provide support for this.

**Comment by jkernech** [comment]
Any update on this one ? Most of the charts require Persistent Volume Claims..

**Comment by jlamillan** [comment]
I have support working here in a local branch. I'm waiting for the volume driver and provisioner to be publicly accessible before I merge.

**Comment by alapidas** [comment]
@jlamillan  The open sourcing work is complete.

**Comment by activeshadow** [comment]
@jlamillan now that the FlexVolume provider and the volume provisioner are open sourced, when do you think you'll be able to merge in your local branch?

**Comment by jlamillan** [comment]
@garthy do you have an update on this? I know you were working on this...

**Comment by garthy** [comment]
I'm currently testing this at the moment.
Should have something tomorrow.

**Comment by activeshadow** [comment]
On Wed, Jan 24, 2018 at 06:53:42PM +0000, Garth Bushell wrote:
> I'm currently testing this at the moment.
> Should have something tomorrow.

FWIW, I manually deployed the OCI FlexVolume Controller on my K8S master
and nodes (running 1.8.6), and deployed the OCI Volume Provisioner
deployment, and all is working just fine.

**Comment by jlamillan** [comment]
Merged.
