### ISSUE TITLE
latest sre installer etcd LBR is setup as private, provide user an option to make it public.

### ISSUE THREAD

**Issue by ddamojip** [oracle/terraform-kubernetes-installer#73]
we used the latest sre installer and noticed that the cluster is setup with etcd LBR as a private LBR

We are concerned that using this setup with a private etcd LBR,  losing network connectivity to that AD with etcd could potentially bring down the service.

SRE installer should provide the user with an option to make it public, so the user can choose how they want it to be setup based on their cluster setup requirements.

**Comment by srvatsam** [comment]
Requesting Steve to help prioritize.

**Comment by jlamillan** [comment]
This issue is resolved with this merge.
