### ISSUE TITLE
With private subnets, nodes come up in not ready state

### ISSUE THREAD

**Issue by srirg** [oracle/terraform-kubernetes-installer#80]
With private subnets, we see that the worker nodes come up in not ready state

worker nodes(1 or 2 or 3) are coming up in NotReady status. 

kubectl get nodes
NAME                                                  STATUS AGE       VERSION
k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com   NotReady 31m       v1.7.4
k8s-worker-ad2-0.k8sworkerad2.k8sbmcs.oraclevcn.com   NotReady 31m       v1.7.4
k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com   NotReady 31m       v1.7.4

Below in the master node journal entries.

Jan 02 17:37:44 k8s-master-ad1-0 kubelet[13086]: W0102 17:37:44.615767   13086 container_manager_linux.go:218] Running with swap on is not supported, please disable swap! This will be a fatal error by default starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.

On the worker nodes journal entries, seeing the below

Jan 02 18:20:05 k8s-worker-ad1-0 kubelet[13436]: E0102 18:20:05.035951   13436 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com' not found
Jan 02 18:20:15 k8s-worker-ad1-0 kubelet[13436]: E0102 18:20:15.073231   13436 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com' not found
Jan 02 18:20:25 k8s-worker-ad1-0 kubelet[13436]: E0102 18:20:25.111192   13436 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com' not found

Noticed that the kube-proxy is not coming up..for another 2 workers nodes are in not ready status now..[opc@k8s-master-ad1-0 ~]$ kubectl get po -n=kube-system
NAME                                                             READY     STATUS    RESTARTS   AGE
kube-dns-2272871451-v3p1r                                        3/3       Running   0          16m
kube-proxy-k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com   1/1       Running   0          14m
kube-proxy-k8s-worker-ad2-0.k8sworkerad2.k8sbmcs.oraclevcn.com   0/1       Unknown   0          14m
kube-proxy-k8s-worker-ad3-0.k8sworkerad3.k8sbmcs.oraclevcn.com   0/1       Pending   0          14m
kubernetes-dashboard-3313488171-1z911                            1/1       Running   0          16m
tiller-deploy-2136207906-kct9c                                   1/1       Running   0          7m

**Comment by jlamillan** [comment]
Confirmed.

**Comment by srirg** [comment]
With the latest OCI reboots happened last week, we're not seeing this issue any more..

**Comment by jlamillan** [comment]
Nice.
