### ISSUE TITLE
Can a worker node have ExternalIP?

### ISSUE THREAD

**Issue by kocic11** [oracle/terraform-kubernetes-installer#87]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.1
+ provider.null v1.0.0
+ provider.oci (unversioned)
+ provider.random v1.1.0
+ provider.template v1.0.0
+ provider.tls v1.0.1

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
terraform-provider-oci 2.0.5
</details>

### Terraform Installer for Kubernetes Version

<details>
# The version/tag/release or commit hash (of this project) the issue occurred on
</details>
34b6c90e2997341f0e6e3eb8ec32ae134e65707d

### Input Variables

<details>
# Values of non-sensitive input variables

</details>

### Description of issue:
A worker node doesn't have ExternalIP. Can it be provisioned or configured after the fact?

**Comment by jlamillan** [comment]
I'm pretty sure that worker nodes that has a pubic IP (i.e. when `control_plane_subnet_access=public` will have a ExternalIP e.g.

```
 kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}'

129.218.42.90 
```

For more information, see the [Network Access Configuration](https://github.com/oracle/terraform-kubernetes-installer/blob/master/docs/input-variables.md#optional-input-variables) section.

**Comment by jlamillan** [comment]
Feel free to reopen this issue if I misunderstood the question.

**Comment by kocic11** [comment]
What do you get when you run

kubectl get nodes -o wide

Also, is public a default setting for control_plane_subnet_access?

**Comment by jlamillan** [comment]
> kubectl get nodes -o wide

```
[root@k8s-master-ad1-0 opc]# kubectl get nodes -o wide
NAME                                                 STATUS    AGE       VERSION   EXTERNAL-IP     OS-IMAGE                  KERNEL-VERSION
k8s-worker-ad1-0.k8sworkerad1.k8soci.oraclevcn.com   Ready     1h        v1.7.10   129.213.50.44   Oracle Linux Server 7.4   4.1.12-112.14.10.el7uek.x86_64
```

> Also, is public a default setting for control_plane_subnet_access?

yes

**Comment by kocic11** [comment]
Very interesting. I ran the installer again and couldn't get the External
IP:

NAME STATUS ROLES AGE VERSION EXTERNAL-IP OS-IMAGE KERNEL-VERSION
> k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com Ready <none> 18m
> v1.7.10 <none> Oracle Linux Server 7.4 4.1.12-112.14.10.el7uek.x86_64


The cluster-check.sh script failed as well:

[cluster-check.sh]   Checking an app deployment of nginx exposed as a
> service...

[cluster-check.sh]    [FAILED] nginx deployment service is not accessible
> on http://xxx.xxx.xx.xxx:32542




Here are the terraform variables I used:

etcd_ssh_ingress = "0.0.0.0/0"
> etcd_cluster_ingress = "10.0.0.0/16"
> master_ssh_ingress = "0.0.0.0/0"
> worker_ssh_ingress = "0.0.0.0/0"
> master_https_ingress = "0.0.0.0/0"
> worker_nodeport_ingress = "0.0.0.0/0"
> control_plane_subnet_access = "public"
> k8s_master_lb_access = "public"
> public_subnet_http_ingress = "0.0.0.0/0"
> public_subnet_https_ingress = "0.0.0.0/0"


What is missing?

**Comment by jlamillan** [comment]
Actually, I believe this issue is due to the fact that your cluster was provisioned _before_ we integrated the [Cloud Controller Manager](https://github.com/oracle/oci-cloud-controller-manager) That’s actually going to be due to the same reason :) which handles querying OCI for additional node addresses. 

Check to see if the `oci-cloud-controller-manager` pod is running:

`kubectl get pods -n kube-system`

If not, try spinning up a new cluster using the latest source.

**Comment by patientplatypus** [comment]
I am also having this issue! If this issue is not open please reopen it!

**Comment by jlamillan** [comment]
@patientplatypus see my comment above.
