### ISSUE TITLE
Is it possible to create multiple kubernetes clusters in a single vcn in a single compartment

### ISSUE THREAD

**Issue by jferr** [oracle/terraform-kubernetes-installer#92]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Terraform Installer for Kubernetes Version

<details>
# The version/tag/release or commit hash (of this project) the issue occurred on
</details>

### Input Variables

<details>
# Values of non-sensitive input variables

</details>

**Comment by jferr** [comment]
Also, please let me know if there is a better forum for this sort of question.  Apologies if this doesn't belong here

**Comment by jlamillan** [comment]
We don't support this currently. Though we do have [this](https://github.com/oracle/terraform-kubernetes-installer/issues/72) issue.

Maybe +1 that issue if you think it is a good idea. The more activity, the more likely the feature will get some traction.
